#!/bin/sh
### BEGIN INIT INFO
# Provides:          habridge
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the habridge.
# Description:       Fast and smalle webserver with minimal memory footprint
#                    developed with security in mind HTTP/1.1 compliant caching
#                    proxy server.
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin

JARDIR="/opt/habridge"
DATADIR="/usr/local/habridge"
PIDFILE="/var/run/habridge.pid"
LOGFILE="/var/log/ha-bridge.log"

init() {
	export JAVA_HOME=/opt/java/
	export PATH=$PATH:$JAVA_HOME/bin
}

case "$1" in
	start)
		echo  -n "Stopping ssdpd for ha-bridge: "
		start-stop-daemon -K -q -p /var/run/ssdpd.pid
		echo "OK"
		if [ ! -e "$DATADIR/data" ] ; then
			mkdir -p $DATADIR/data
		fi
		if [ ! -e "$JARDIR/data" ] ; then
			mount / -o remount,rw
			ln -s $DATADIR/data $JARDIR/data
			mount / -o remount,ro
		fi
		cd $JARDIR
		if [ -e "$LOGFILE" ] ; then
			rm -rf $LOGFILE
		fi
		init
		echo -n "Starting HA-bridge: "
		start-stop-daemon -b -S -q -m -p $PIDFILE --exec java -- -jar -Dserver.port=8080 -Dconfig.file=data/habridge.config $JARDIR/ha-bridge.jar > $LOGFILE 2>&1 &
		echo "OK"
		chmod 777 $LOGFILE
		;;
	stop)
		echo -n "Stopping HA-bridge: "
		start-stop-daemon -K -q -p $PIDFILE
		if [ -e "$PIDFILE" ] ; then
			rm -rf $PIDFILE
		fi
		echo "OK"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
		exit 1
		;;
esac

exit 0
